name: Deploy
on:
    push:
        branches: [master]

jobs:
    deploy:
        name: Deploy
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v3

            - name: Install Dependencies
              run: npm i

            - name: Build
              run: npm run build

            - name: Move Built Files to Corresponding Folder
              run: |
                  rm -rf /var/notes/bijanprogrammer.com/html/web
                  cp -a build/. /var/notes/bijanprogrammer.com/html/web
